version: '2'

services:
  shell:
    image: tensorflow/tensorflow
    hostname: 'shell'
    volumes:
      - /home/dunkyfool/Projects/tmp/pokergame:/notebooks/pokergame
    ports: 
      - 8888:8888
      - 6006:6006
